# Site settings
baseurl = "/"
languageCode = "fi-fi"
title = "Opetus.tv pelit"
theme = "metro-bootstrap"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXXXXX-Y"

pygmentsStyle = "native"

[params]
    # Meta
    title = "Opetus.tv:n pelit"
    author = "Opetus.tv"
    description = "Opetus.tv:n pelisivusto sisältää matemaattis-luonnontieteellisiä pelejä."
    keywords = "opetus,opetustv,peli,pelit,matematiikka,fysiikka,kemia,pentomino,polynomio,tangram"
